name: Deploy
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - uses: D3rHase/ssh-command-action@latest
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        command: |
          cd interpreter;
          git pull;
          docker kill $(docker ps | grep code-server | awk '{ print $1 }');
          cd server;
          docker build --tag code-server .;
          docker run -d -p 8080:8080 code-server
