name: Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - uses: D3rHase/ssh-command-action@latest
      with:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST_FINGERPRINT: ${{ secrets.HOST_FINGERPRINT }}
        command: |
          cd interpreter
          git pull
          docker kill code-server
          docker run -d -p 8080:8080 code-server
          docker run -d -p 8080:8080 code-server
